### ISSUE TITLE
Latest release doesn't match latest code

### ISSUE THREAD

**Issue by kand** [j0hnsmith/django-pipeline-browserify#12]
The latest release on pypi is 0.2.0, which doesn't represent the latest code in this repo at 0.3.0.

**Comment by ramusus** [comment]
:+1: please update version in pypi

**Comment by natevw** [comment]
Hmm, now the [latest release on PyPi](https://pypi.python.org/pypi/django-pipeline-browserify) is 0.4.0, which is _newer_ than the setup.py file here? @j0hnsmith could you please clarify what the status of this library is?

**Comment by j0hnsmith** [comment]
Ahh, I didn't realise that. I created a new release on pypi but forgot to push to github, that's why the code here was behind Pypi. Then I merged a branch on github (not realising that master wasn't up to date).

I've just added a new release, `0.4.1`, to Pypi and pushed the code to github. Sorry for any confusion.
